"""initial schema

Revision ID: 866507e290ed
Revises: 
Create Date: 2026-01-09 12:46:32.015184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '866507e290ed'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_blacklist',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('normalized_email', sa.String(length=255), nullable=False),
    sa.Column('reason', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('normalized_email')
    )
    op.create_index('idx_blacklist_expires_at', 'email_blacklist', ['expires_at'], unique=False)
    op.create_index('idx_blacklist_normalized_email', 'email_blacklist', ['normalized_email'], unique=True)
    op.create_index(op.f('ix_email_blacklist_expires_at'), 'email_blacklist', ['expires_at'], unique=False)
    op.create_table('magic_link_tokens',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('normalized_email', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('generation_ip', sa.String(length=45), nullable=True),
    sa.Column('usage_ip', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index('idx_magic_expires_at', 'magic_link_tokens', ['expires_at'], unique=False)
    op.create_index('idx_magic_normalized_email', 'magic_link_tokens', ['normalized_email'], unique=False)
    op.create_index('idx_magic_token_hash', 'magic_link_tokens', ['token_hash'], unique=True)
    op.create_table('manual_resolution',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('payment_id', sa.String(length=255), nullable=False),
    sa.Column('user_email', sa.String(length=255), nullable=False),
    sa.Column('normalized_email', sa.String(length=255), nullable=False),
    sa.Column('issue_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('sla_deadline', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('assigned_to', sa.String(length=255), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_manual_created_at', 'manual_resolution', ['created_at'], unique=False)
    op.create_index('idx_manual_sla_deadline', 'manual_resolution', ['sla_deadline'], unique=False)
    op.create_index('idx_manual_status', 'manual_resolution', ['status'], unique=False)
    op.create_index(op.f('ix_manual_resolution_created_at'), 'manual_resolution', ['created_at'], unique=False)
    op.create_index(op.f('ix_manual_resolution_normalized_email'), 'manual_resolution', ['normalized_email'], unique=False)
    op.create_index(op.f('ix_manual_resolution_sla_deadline'), 'manual_resolution', ['sla_deadline'], unique=False)
    op.create_table('meal_plans',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('payment_id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('normalized_email', sa.String(length=255), nullable=False),
    sa.Column('pdf_blob_path', sa.Text(), nullable=False),
    sa.Column('calorie_target', sa.Integer(), nullable=False),
    sa.Column('preferences_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ai_model', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('refund_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('email_sent_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payment_id')
    )
    op.create_index('idx_mealplan_created_at', 'meal_plans', ['created_at'], unique=False)
    op.create_index('idx_mealplan_normalized_email', 'meal_plans', ['normalized_email'], unique=False)
    op.create_index('idx_mealplan_payment_id', 'meal_plans', ['payment_id'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('normalized_email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('idx_user_email', 'users', ['email'], unique=True)
    op.create_index('idx_user_normalized_email', 'users', ['normalized_email'], unique=False)
    op.create_index(op.f('ix_users_normalized_email'), 'users', ['normalized_email'], unique=False)
    op.create_table('payment_transactions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('payment_id', sa.String(length=255), nullable=False),
    sa.Column('meal_plan_id', sa.String(), nullable=True),
    sa.Column('amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=False),
    sa.Column('payment_status', sa.String(length=50), nullable=False),
    sa.Column('paddle_created_at', sa.DateTime(), nullable=False),
    sa.Column('webhook_received_at', sa.DateTime(), nullable=False),
    sa.Column('customer_email', sa.String(length=255), nullable=False),
    sa.Column('normalized_email', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['meal_plan_id'], ['meal_plans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payment_id')
    )
    op.create_index('idx_payment_normalized_email', 'payment_transactions', ['normalized_email'], unique=False)
    op.create_index('idx_payment_paddle_created_at', 'payment_transactions', ['paddle_created_at'], unique=False)
    op.create_index('idx_payment_status', 'payment_transactions', ['payment_status'], unique=False)
    op.create_index('idx_payment_transaction_id', 'payment_transactions', ['payment_id'], unique=True)
    op.create_table('quiz_responses',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('normalized_email', sa.String(length=255), nullable=False),
    sa.Column('quiz_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('calorie_target', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('payment_id', sa.String(length=255), nullable=True),
    sa.Column('pdf_delivered_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_quiz_created_at', 'quiz_responses', ['created_at'], unique=False)
    op.create_index('idx_quiz_normalized_email', 'quiz_responses', ['normalized_email'], unique=False)
    op.create_index('idx_quiz_pdf_delivered_at', 'quiz_responses', ['pdf_delivered_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_quiz_pdf_delivered_at', table_name='quiz_responses')
    op.drop_index('idx_quiz_normalized_email', table_name='quiz_responses')
    op.drop_index('idx_quiz_created_at', table_name='quiz_responses')
    op.drop_table('quiz_responses')
    op.drop_index('idx_payment_transaction_id', table_name='payment_transactions')
    op.drop_index('idx_payment_status', table_name='payment_transactions')
    op.drop_index('idx_payment_paddle_created_at', table_name='payment_transactions')
    op.drop_index('idx_payment_normalized_email', table_name='payment_transactions')
    op.drop_table('payment_transactions')
    op.drop_index(op.f('ix_users_normalized_email'), table_name='users')
    op.drop_index('idx_user_normalized_email', table_name='users')
    op.drop_index('idx_user_email', table_name='users')
    op.drop_table('users')
    op.drop_index('idx_mealplan_payment_id', table_name='meal_plans')
    op.drop_index('idx_mealplan_normalized_email', table_name='meal_plans')
    op.drop_index('idx_mealplan_created_at', table_name='meal_plans')
    op.drop_table('meal_plans')
    op.drop_index(op.f('ix_manual_resolution_sla_deadline'), table_name='manual_resolution')
    op.drop_index(op.f('ix_manual_resolution_normalized_email'), table_name='manual_resolution')
    op.drop_index(op.f('ix_manual_resolution_created_at'), table_name='manual_resolution')
    op.drop_index('idx_manual_status', table_name='manual_resolution')
    op.drop_index('idx_manual_sla_deadline', table_name='manual_resolution')
    op.drop_index('idx_manual_created_at', table_name='manual_resolution')
    op.drop_table('manual_resolution')
    op.drop_index('idx_magic_token_hash', table_name='magic_link_tokens')
    op.drop_index('idx_magic_normalized_email', table_name='magic_link_tokens')
    op.drop_index('idx_magic_expires_at', table_name='magic_link_tokens')
    op.drop_table('magic_link_tokens')
    op.drop_index(op.f('ix_email_blacklist_expires_at'), table_name='email_blacklist')
    op.drop_index('idx_blacklist_normalized_email', table_name='email_blacklist')
    op.drop_index('idx_blacklist_expires_at', table_name='email_blacklist')
    op.drop_table('email_blacklist')
    # ### end Alembic commands ###
